#!/bin/bash

myid_src () {
bot_retorno="====================\n"
          bot_retorno+="SU ID: ${chatuser}\n"
          bot_retorno+="====================\n"
msj_fun
}

deleteID_reply () {
delid=$(sed -n ${message_text[$id]}p ${CID})
sed -i "${message_text[$id]}d" ${CID}
bot_retorno="$LINE\n"
          bot_retorno+="ID eliminado exitosamente.\n"
          bot_retorno+="ID: ${delid}\n"
          bot_retorno+="$LINE\n"
msj_fun
upfile_src
}

addID_reply () {
      [[ $(cat ${CID}|grep "${message_text[$id]}") = "" ]] && {
        echo "/${message_text[$id]}" >> ${CID}
          bot_retorno="$LINE\n"
          bot_retorno+="✅ *ID agregado * ✅\n"
          bot_retorno+="$LINE\n"
          bot_retorno+="$(< ${CID})\n"
          bot_retorno+="$LINE\n"
          bot_retorno+="New ID: ${message_text[$id]}\n"
          bot_retorno+="$LINE"

          bot_retor="$LINE\n"
          bot_retor+="💎El owner @drowkid01 autorizo tu acceso al bot💎\n"
          bot_retor+="$LINE\n"
          bot_retor+="😎Welcome admin😎\n"
          bot_retor+="Usa /menu para ver todas mis habilidades!\n"
          bot_retor+="$LINE\n"
      msj_fun
      msj_add ${message_text[$id]}
      upfile_src
    } || {
          bot_retorno="====ERROR====\n"
          bot_retorno+="Este ID ya existe\n"
          bot_retorno+="$LINE\n"
      msj_fun
    }
}










