#!/bin/bash
link_src () {
	bot_retorno="$LINE\n"
	bot_retorno+="   🧬🧬 Soporte - OS 🧬🧬 \n  Ubuntu 14 - 16 - 18 - 20 (x64)\n          Debian 7,8,9,10 (x64) \n 𝙍𝙚𝙘𝙤𝙢𝙚𝙣𝙙𝙖𝙙𝙤 𝙐𝙗𝙪𝙣𝙩𝙪 18.04 \n  🪦 Soliciar créditos. 🛡️⚔️\n"
	bot_retorno+="Verifica tus Keys, https://t.me/drowkid01 Reseller : @drowkid01 \n"
	bot_retorno+="$LINE\n"
	bot_retorno+="<code>apt-get update && apt-get upgrade -y && wget https://raw.githubusercontent.com/drowkid-1/framework/main/inst-dk1/init && chmod 777 init && ./init --drowkid</code>\n"
	bot_retorno+="$LINE\n"
	bot_retorno+="$LINE\n"
	bot_retorno+="  🛡️  𝙸𝚗𝚜𝚝𝚊𝚕𝚊𝚍𝚘𝚛  𝙾𝚏𝚒𝚌𝚒𝚊𝚕 $(cat < /etc/SCRIPT/v-local.log) FOR ARM 🛡️ \n"
	bot_retorno+="$LINE\n"
	bot_retorno+="<code>apt-get update && apt-get upgrade -y && wget https://raw.githubusercontent.com/drowkid-1/framework/main/inst-dk1/init && chmod 777 init && ./init --drowkid</code>\n"
msj_fun
}
